### ISSUE TITLE
Support for PyTorch 2.0+

### ISSUE THREAD

**Issue by Emrys365** [Takaaki-Saeki/DiscreteSpeechMetrics#2]
Hi,

Thanks for releasing this very interesting model!
I see that the current code only works for PyTorch 1.10.1 ~ 1.13.0. Would you also consider supporting newer PyTorch versions such as 2.0+. It would be very helpful for people who only have PyTorch 2.0+ in their environment as they don't have to install a new environment for running this evaluation.

**Comment by Takaaki-Saeki** [comment]
Thanks for the great suggestion!
I initially restricted the code to PyTorch < 2 to avoid warnings, but it turned out to be a false alarm.
So I have updated the supported PyTorch version as you pointed out.
See the pull request below for more details.
https://github.com/Takaaki-Saeki/DiscreteSpeechMetrics/pull/3

So please try the latest version. If you have any other issues, please let me know.
